name: PartyAnimals
version: "0.3.0"
main: com.muhdfdeen.partyanimals.PartyAnimals
description: A highly customizable Minecraft plugin that spawn pinata entities that players can defeat for configurable, chance-based rewards.
author: muhdfdeen
website: https://github.com/muhdfdeen/partyanimals
api-version: "1.21"
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false