name: PartyAnimals
version: "1.4.1"
main: org.maboroshi.partyanimals.PartyAnimals
loader: org.maboroshi.partyanimals.util.LibraryLoader
description: A highly customizable Minecraft plugin that spawn pinata entities that players can defeat for configurable, chance-based rewards.
author: Maboroshi
website: https://github.com/MaboroshiKobo/PartyAnimals
api-version: "1.21"
dependencies:
  server:
    PlaceholderAPI:
      load: BEFORE
      required: false
    Votifier:
      load: BEFORE
      required: false